# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c682ac9e761661fa2a3e4317981733119bf3fa10321dc90303eb854493ae846c31efd91105c631aa4d9ea29d9bfc7d91dbfd62501f5c529200915ce1b45268c5

test:
  secret_key_base: c1d31be4c576ec1be5bc5dbddd824650de68096280959d55a6ef9d4693f642948474db074b8460d960f2be0126c37c1aef91c0ae4582739fcb220bb54061e93c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
